---

- name: Add java repo
  apt_repository: repo="ppa:openjdk-r/ppa"
  tags:
      - java

- name: Add openjdk 8
  apt: name=openjdk-8-jdk
  tags:
      - java

- name: Install stuff
  apt: name={{item}}
  with_items:
      - tar
      - wget
      - git
      - build-essential
      - python-dev
      - libcurl4-nss-dev
      - libsasl2-dev
      - libsasl2-modules
      - maven 
      - libapr1-dev
      - libsvn-dev

- name: Confirm hostname exists
  lineinfile:
      dest: /etc/hosts
      regexp: "^{{ ansible_default_ipv4.address}}"
      line: "{{ansible_default_ipv4.address}} {{ansible_hostname}}"

- name: Add mesos list
  copy:
      dest: /etc/apt/sources.list.d/mesosphere.list
      content: deb http://repos.mesosphere.com/ubuntu trusty main

- name: Install mesos
  apt:
      name: mesos=0.28.2-2.0.27.ubuntu1404

