- name: Confirm hostname exists
  lineinfile:
      dest: /etc/hosts
      regexp: "^{{ ansible_default_ipv4.address}}"
      line: "{{ansible_default_ipv4.address}} {{ansible_hostname}}"

- name: Install mesos
  apt:
      name: mesos=0.28.2-2.0.27.ubuntu1404

- name: Add java repo
  apt_repository: repo="ppa:openjdk-r/ppa"
  tags:
      - java

- name: Add openjdk 8
  apt: name=openjdk-8-jdk
  tags:
      - java
