---


- name: Make mesos volume path
  file:
      path: "{{volume_path}}/mesos"
      state: directory
  notify: restart slave

- name: Change workdir to volume
  copy:
      dest: /etc/mesos-slave/work_dir
      content: /media/volume/mesos
  notify: restart slave

- name: Add zk
  copy:
      dest: /etc/mesos/zk
      content: "zk://{{ groups['mesos-master']|join(':2181,') }}:2181/mesos"
  notify: restart slave
  tags:
      - zk

- name: Add docker container options
  copy:
      dest: /etc/mesos-slave/containerizers
      content: "docker,mesos"
  notify: restart slave

- name: Add isolation
  copy:
      dest: /etc/mesos-slave/isolation
      content: "cgroups/cpu,cgroups/mem"
  notify: restart slave

# Needs to be done unless you have DNS
- name: Set hostname to ip
  copy:
      dest: /etc/mesos-slave/hostname
      content: "{{ansible_default_ipv4.address}}"
  notify: restart slave

- name: Add ip
  copy:
      dest: /etc/mesos-slave/ip
      content: "{{ansible_default_ipv4.address}}"
  notify: restart slave



