---
- hosts: mesos-master mesos-followers
  user: root
  roles:
      - common

- hosts: mesos-master
  user: root
  roles:
      - master

- hosts: mesos-followers
  user: root
  roles:
      - follower
