---
- hosts: mesos-master mesos-followers
  user: root
  roles:
      - common

- hosts: mesos-master
  user: root
  roles:
      - master

- hosts: mesos-followers
  user: root
  vars:
      # Where attached volume is on host
      - volume_path: /media/volume
  roles:
      - follower
      - mesos-dns
